version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gsuite-mcp
    binary: gsuite-mcp
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - docs/*
      - product-description.md

brews:
  - repository:
      owner: 2389-research
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/2389-research/gsuite-mcp"
    description: "GSuite MCP Server - Model Context Protocol server for Google Workspace APIs"
    install: |
      bin.install "gsuite-mcp"
    test: |
      system "#{bin}/gsuite-mcp", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
